[versions]
gson = "2.13.1"
plugin-publish = "2.0.0"
foojay-resolver = "0.9.0"
junit = "5.11.4"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
